### ISSUE TITLE
Extra elements shown on customiser that are not meant to be shown

### ISSUE THREAD

**Issue by carlosvirreira** [Whale-Agency/configurator#6]
Issa huge picture I know, sorry but thats how I can show it to you. 

![Screenshot 2021-09-29 at 13 37 10](https://user-images.githubusercontent.com/12449255/135261006-618d2fb4-3b23-4cbf-a84e-bf40ee653f9c.png)

**Comment by DonKoko** [comment]
Solved. Will deploy it with the rest of the changes in a bit
